### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by marshalleq** [RenoFischa/idrive#2]
I'm having some issues where I can login, but the backup client never shows up in the dashboard, thus, I can never back any files up.  An obvious thing to check is if I'm running the latest version of idrive, which I'm clearly not.

It appears that this docker image is running 2.37 and the latest version for linux is 3.2.0.

I'm meant to be able to run from /opt/IDriveForLinux/bin
./idrive -C to check for an update

But I can't seem to find the idrive executable anywhere.

I've also tried restarting the container, checking I'm running latest etc, but no luck.

(This is on TrueNAS scale BTW, not that that should matter).

Any help would be appreciated.

Many thanks,

Marshalleq

**Comment by marshalleq** [comment]
I have just discovered the check_for_update.pl script.  I swear I looked for that multiple times.  Oh well!  Trying now.

**Comment by marshalleq** [comment]
Just a note for others coming here, this requires multiple updates.  The second pass actually creates an error, then you run it again and finally it get's to version 3.2.

After that it says to run it as per below.  And finally I can see my computer in the idrive dashboard.

/opt/IDriveForLinux/bin and run ./idrive to continue. To update, run /tmp/idriveforlinux.bin --update.

This unfortunately doesn't survive reboots and we are left with a non-functioning container again. I'm not sure my hackery is going to be good enough to fix this and probably should be done by the owner of this docker image - or perhaps find another (newer) docker image.

**Comment by RenoFischa** [comment]
Thanks for posting a temporary update solution.
I'll look into updating the container. Since they switched from perl scripts to precompiled bin executeables, it won't be that easy because the file structure has changed and I don't know yet which files need to be persistent.
But I'll try to make it happen.

**Comment by LunkSnee** [comment]
I wish I knew github better - but I don't. I've forked this and modified it to work w v3.2 of idrive. my updated docker image is working for me. I'm happy to submit a pull request, but I don't know how to limit the pull request to just the needed changes and not my other tweaks to documentation, etc.
https://github.com/LunkSnee/idrive-persist

**Comment by RenoFischa** [comment]
@marshalleq Did you need to reconfigure your account and which files to backup after updating?

**Comment by RenoFischa** [comment]
@LunkSnee thanks for your input!
I've pushed an updated image with tag `3.2` This now contains the idrive binaries version 3.2.
A few changed need to be made to the container configuration for the new version. The required changes are listed at the bottom of the Readme.
If you happen to start the container with the new version before making the changes, just stop it again and make the changes. It should still work.
Tag `latest` still contains the old version. If nobody reports any issues for the next week or so I'll push the new version to lastest as well.

**Comment by RenoFischa** [comment]
Tag ``latest`` is now also v3
